CREATE SEQUENCE SEQ_REPLY;

CREATE TABLE TBL_REPLY(
	REPLY_NUMBER NUMBER(10),
	BOARD_BNO NUMBER(10) NOT NULL,
	REPLY_CONTENT VARCHAR2(2000) NOT NULL,
	REPLY_WRITER VARCHAR2(1000) NOT NULL,
	REPLY_REGISTER_DATE DATE DEFAULT SYSDATE, 
	REPLY_UPDATE_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_TBL_REPLY_BOARD_BNO FOREIGN KEY(BOARD_BNO)
	REFERENCES TBL_BOARD(BOARD_BNO) ON DELETE CASCADE
);

ALTER TABLE TBL_REPLY ADD CONSTRAINT PK_REPLY PRIMARY KEY(REPLY_NUMBER);

SELECT * FROM TBL_REPLY;